// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ67hyYglcHdQ8B9fdAJZeLIZXSHJMUvo',
    appId: '1:577373731371:web:35657fcfa35489a380c86e',
    messagingSenderId: '577373731371',
    projectId: 'laporyuk-uas',
    authDomain: 'laporyuk-uas.firebaseapp.com',
    storageBucket: 'laporyuk-uas.firebasestorage.app',
    measurementId: 'G-GQ4SKF84S9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHa89eCxtu6_hvRanle425ax83Dx4s62o',
    appId: '1:577373731371:android:e032adc42e97e49380c86e',
    messagingSenderId: '577373731371',
    projectId: 'laporyuk-uas',
    storageBucket: 'laporyuk-uas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYfF_ev53F4Wj76WDGmHk8u4gSXYEZ10w',
    appId: '1:577373731371:ios:74027c3c6fd0bf4180c86e',
    messagingSenderId: '577373731371',
    projectId: 'laporyuk-uas',
    storageBucket: 'laporyuk-uas.firebasestorage.app',
    iosBundleId: 'com.example.flutterUas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYfF_ev53F4Wj76WDGmHk8u4gSXYEZ10w',
    appId: '1:577373731371:ios:74027c3c6fd0bf4180c86e',
    messagingSenderId: '577373731371',
    projectId: 'laporyuk-uas',
    storageBucket: 'laporyuk-uas.firebasestorage.app',
    iosBundleId: 'com.example.flutterUas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ67hyYglcHdQ8B9fdAJZeLIZXSHJMUvo',
    appId: '1:577373731371:web:65b2e584a19ab2da80c86e',
    messagingSenderId: '577373731371',
    projectId: 'laporyuk-uas',
    authDomain: 'laporyuk-uas.firebaseapp.com',
    storageBucket: 'laporyuk-uas.firebasestorage.app',
    measurementId: 'G-KEL3QP9SB5',
  );
}
